[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR"

[tool.pylint.main]
# Python code to execute, usually for sys.path manipulation such as
# pygtk.require().
init-hook ="import sys; sys.path.append('.')"

# Minimum Python version to use for version dependent checks. Will default to the
# version used to run pylint.
py-version = "3.10"
